spring:
    application.name: HistoryService

    jpa.hibernate.ddl-auto: update
    
    datasource: 
        url: jdbc:h2:file:./data/pb_tp1_historyServicedb;
        driverClassName: org.h2.Driver
        username: joao_ramos_h
        password: 12345678_h

    rabbitmq:
        host: localhost 
        port: 5672
        username: EvBrokerJoao_Ramos_PB
        password: 12345678_ev

server:
    port: 8081